function Daily_Notification(source,eventdata)
close all
%Contact server to get data
my_weather = Contact_Server;
%Create Final GUI to display weather
Daily_Notification_GUI = figure ('Visible', 'off', 'color', 'white');
%Move Gui to the center of the screen.
movegui(Daily_Notification_GUI, 'center');
Figure_Handle5 = gcf;
set(Figure_Handle5, 'NumberTitle', 'off');
set(Daily_Notification_GUI,'Name','Weather Notification',...
    'Resize','off');
%Use if statement to set the background of the GUI based upon the weather.
Image_data5 = imread('Fall.jpg', 'jpg');
axes
imagesc(Image_data5)
set(gca, 'YTick',[],'XTick',[], 'YTickLabel',[], ...
    'XTickLabel',[],'YColor', [1 1 1],'XColor', [1 1 1])
set(gcf,'MenuBar','none');

Temperatures = uicontrol('Style','text','Position',[65,35,460,18],...
    'String',sprintf('Current Temperature: %c%cF Max Temperature: %c%cF Min Temperature: %c%cF',...
    my_weather(3:4),my_weather(6:7),my_weather(9:10)),'FontName', ...
    'TimesNewRoman','FontSize',10,'FontWeight','Bold');

Wind = uicontrol('Style','text','Position',[70,17,450,18],'String',...
    sprintf('Humidty: %c%c%% Wind speed range: %c%c - %c%cmph Percipitation: %c%c%c%c inches',...
    my_weather(12:13),my_weather(19:20),my_weather(22:23),my_weather(15:18)),...
    'FontName', 'TimesNewRoman','FontSize',10,'FontWeight','Bold');
% 
% Notification_Text = uicontrol('Style','text','Position',[80,30,435,20],...
%     'String','Hurry up or you will be screwed',...
%  'FontName', 'TimesNewRoman','FontSize',10,'FontWeight','Bold');

Go_Back_Button = uicontrol('Style','pushbutton','String',...
    'Back','Position',[40,450,120,20], 'FontName', ...
    'TimesNewRoman','FontSize',10,'Callback',...
    @Notification_Preferences );

Refresh_Weather_Forecast= uicontrol('Style','pushbutton','String',...
    'Refresh','Position',[400,450,120,20], 'FontName', ...
    'TimesNewRoman','FontSize',10,'Callback',...
    @Daily_Notification);

set(Daily_Notification_GUI,'Visible', 'on');
end

